---

version: '3'

services:
  exercises:
    build: .
    # TODO: replace exercises-template with "exercises-<language>"
    image: hexletbasics/exercises-layout-designer:cached
    command: make check
